steps:


  - label: ":scroll: Run tests for Julia v{{matrix.version}}"
    env:
      JULIA_VERSION: "{{matrix.version}}"
      JULIA_DEPOT: "$DEPOT/{{matrix.version}}"
    commands:
      - "echo 'Running tests with Depot located at $DEPOT/{{matrix.version}}'"
      - "srun --cpus-per-task=16 --mem=64G --time=1:00:00 --unbuffered .buildkite/run_tests.sh {{matrix.version}}"
    matrix:
      setup:
        version:
          - "$JULIA_LTS"
          - "$JULIA_LATEST"

  - wait

  - label: ":scroll: Build docs for Julia v{{matrix.version}}"
    env:
      JULIA_PROJECT: "docs/"
      JULIA_VERSION: "{{matrix.version}}"
      JULIA_DEPOT: "$DEPOT/{{matrix.version}}"
    commands:
      - "echo 'Building docs with Depot located at $DEPOT/{{matrix.version}}'"
      - "srun --cpus-per-task=16 --mem=64G --time=1:00:00 --unbuffered .buildkite/build_docs.sh {{matrix.version}}"
    matrix:
      setup:
        version:
          - "$JULIA_LTS"

  - wait
