name: Julia Release Package
on:
  workflow_call:
    secrets:
      SERVICE_TOKEN:
        description: "Token to use for Project.toml update push"
        required: false
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/RegisterAction@latest
        with:
          token: ${{ secrets.SERVICE_TOKEN }}
