name: Julia CI
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: "Token for the repository from codecov.io for uploading the code coverage report"
        required: false
    inputs:
      codecov:
        description: "Whether or not to include codecov"
        default: true
        required: false
        type: boolean
      docs:
        description: "Whether or not to build and deploy Documenter.jl docs"
        default: true
        required: false
        type: boolean
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ["1"]
        os: [ubuntu-latest]
        arch: ["x64", "x86"]
        include:
          # test macOS and Windows with latest Julia only
          - os: macOS-latest
            arch: x64
            version: 1
          - os: windows-latest
            arch: x64
            version: 1
          - os: windows-latest
            arch: x86
            version: 1

    steps:
      - uses: actions/checkout@v2
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - name: "Run tests"
        uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
        if: ${{ inputs.codecov }}
      - uses: codecov/codecov-action@v3
        if: ${{ inputs.codecov }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  docs:
    name: Documentation
    if: ${{ inputs.docs }}
    runs-on: ubuntu-latest
    env:
      # GR backend fix for Plots, discussed in https://github.com/jheinen/GR.jl/issues/422
      GKSwstype: nul
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - name: "Install system dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install graphviz pdf2svg
          sudo apt-get install texlive-latex-base texlive-latex-extra texlive-binaries texlive-pictures texlive-luatex
      - name: "Install Julia dependencies"
        run: julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate();'
      - name: "Build and deploy docs"
        run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
