name: Julia TagBot
on:
  workflow_call:
    secrets:
      DOCUMENTER_KEY:
        description: "Privileged key for TagBot"
        required: false
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
